<?php

use Illuminate\Database\Seeder;
use App\Models\GalleryPlaces;
class GalleryPlacesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $images=[
            [
                'place_id'=>1,
                'url'=>"bioparques/amacayacu/amacayacu-1.jpg"
            ],
            [
                'place_id'=>1,
                'url'=>"bioparques/amacayacu/amacayacu-2.jpg"
            ],
            [
                'place_id'=>1,
                'url'=>"bioparques/amacayacu/amacayacu-3.jpg"
            ],
            [
                'place_id'=>1,
                'url'=>"bioparques/amacayacu/amacayacu-4.jpg"
            ],
            [
                'place_id'=>1,
                'url'=>"bioparques/amacayacu/amacayacu-5.jpg"
            ],
            [
                'place_id'=>2,
                'url'=>"bioparques/caboVela/caboVela-1.jpg"
            ],
            [
                'place_id'=>2,
                'url'=>"bioparques/caboVela/caboVela-2.jpg"
            ],
            [
                'place_id'=>2,
                'url'=>"bioparques/caboVela/caboVela-3.jpg"
            ],
            [
                'place_id'=>2,
                'url'=>"bioparques/caboVela/caboVela-4.jpg"
            ],
            [
                'place_id'=>2,
                'url'=>"bioparques/caboVela/caboVela-5.jpg"
            ],
            [
                'place_id'=>3,
                'url'=>"bioparques/cahuinari/cahuinari-1.jpg"
            ],
            [
                'place_id'=>3,
                'url'=>"bioparques/cahuinari/cahuinari-2.jpg"
            ],
            [
                'place_id'=>3,
                'url'=>"bioparques/cahuinari/cahuinari-3.jpg"
            ],
            [
                'place_id'=>3,
                'url'=>"bioparques/cahuinari/cahuinari-4.jpg"
            ],
            [
                'place_id'=>3,
                'url'=>"bioparques/cahuinari/cahuinari-5.jpg"
            ],
            [
                'place_id'=>4,
                'url'=>"bioparques/chingaza/chingaza-1.jpg"
            ],
            [
                'place_id'=>4,
                'url'=>"bioparques/chingaza/chingaza-2.jpg"
            ],
            [
                'place_id'=>4,
                'url'=>"bioparques/chingaza/chingaza-3.jpg"
            ],
            [
                'place_id'=>4,
                'url'=>"bioparques/chingaza/chingaza-4.jpg"
            ],
            [
                'place_id'=>4,
                'url'=>"bioparques/chingaza/chingaza-5.jpg"
            ],
            [
                'place_id'=>5,
                'url'=>"bioparques/cocora/cocora-1.jpg"
            ],
            [
                'place_id'=>5,
                'url'=>"bioparques/cocora/cocora-2.jpg"
            ],
            [
                'place_id'=>5,
                'url'=>"bioparques/cocora/cocora-3.jpg"
            ],
            [
                'place_id'=>5,
                'url'=>"bioparques/cocora/cocora-4.jpg"
            ],
            [
                'place_id'=>5,
                'url'=>"bioparques/cocora/cocora-5.jpg"
            ],
            [
                'place_id'=>6,
                'url'=>"bioparques/cocuy/cocuy-1.jpg"
            ],
            [
                'place_id'=>6,
                'url'=>"bioparques/cocuy/cocuy-2.jpg"
            ],
            [
                'place_id'=>6,
                'url'=>"bioparques/cocuy/cocuy-3.jpg"
            ],
            [
                'place_id'=>6,
                'url'=>"bioparques/cocuy/cocuy-4.jpg"
            ],
            [
                'place_id'=>6,
                'url'=>"bioparques/cocuy/cocuy-5.jpg"
            ],
            [
                'place_id'=>7,
                'url'=>"bioparques/coralesRosario/coralesRosario-1.jpg"
            ],
            [
                'place_id'=>7,
                'url'=>"bioparques/coralesRosario/coralesRosario-2.jpg"
            ],
            [
                'place_id'=>7,
                'url'=>"bioparques/coralesRosario/coralesRosario-3.jpg"
            ],
            [
                'place_id'=>7,
                'url'=>"bioparques/coralesRosario/coralesRosario-4.jpg"
            ],
            [
                'place_id'=>7,
                'url'=>"bioparques/coralesRosario/coralesRosario-5.jpg"
            ],
            [
                'place_id'=>8,
                'url'=>"bioparques/corota/corota-1.jpg"
            ]
            ,
            [
                'place_id'=>8,
                'url'=>"bioparques/corota/corota-2.jpg"
            ]
            ,
            [
                'place_id'=>8,
                'url'=>"bioparques/corota/corota-3.jpg"
            ]
            ,
            [
                'place_id'=>8,
                'url'=>"bioparques/corota/corota-4.jpg"
            ]
            ,
            [
                'place_id'=>8,
                'url'=>"bioparques/corota/corota-5.jpg"
            ],
            [
                'place_id'=>9,
                'url'=>"bioparques/farallones/farallones-1.jpg"
            ]
            ,
            [
                'place_id'=>9,
                'url'=>"bioparques/farallones/farallones-2.jpg"
            ]
            ,
            [
                'place_id'=>9,
                'url'=>"bioparques/farallones/farallones-3.jpg"
            ]
            ,
            [
                'place_id'=>9,
                'url'=>"bioparques/farallones/farallones-4.jpg"
            ]
            ,
            [
                'place_id'=>9,
                'url'=>"bioparques/farallones/farallones-5.jpg"
            ],
            [
                'place_id'=>10,
                'url'=>"bioparques/galeras/galeras-1.jpg"
            ]
            ,
            [
                'place_id'=>10,
                'url'=>"bioparques/galeras/galeras-2.jpg"
            ]
            ,
            [
                'place_id'=>10,
                'url'=>"bioparques/galeras/galeras-3.jpg"
            ]
            ,
            [
                'place_id'=>10,
                'url'=>"bioparques/galeras/galeras-4.jpg"
            ]
            ,
            [
                'place_id'=>10,
                'url'=>"bioparques/galeras/galeras-5.jpg"
            ],
            [
                'place_id'=>11,
                'url'=>"bioparques/iguaque/iguaque-1.jpg"
            ]
            ,
            [
                'place_id'=>11,
                'url'=>"bioparques/iguaque/iguaque-2.jpg"
            ]
            ,
            [
                'place_id'=>11,
                'url'=>"bioparques/iguaque/iguaque-3.jpg"
            ]
            ,
            [
                'place_id'=>11,
                'url'=>"bioparques/iguaque/iguaque-4.jpg"
            ]
            ,
            [
                'place_id'=>11,
                'url'=>"bioparques/iguaque/iguaque-5.jpg"
            ],
            [
                'place_id'=>12,
                'url'=>"bioparques/losNevados/losNevados-1.jpg"
            ]
            ,
            [
                'place_id'=>12,
                'url'=>"bioparques/losNevados/losNevados-2.jpg"
            ]
            ,
            [
                'place_id'=>12,
                'url'=>"bioparques/losNevados/losNevados-3.jpg"
            ]
            ,
            [
                'place_id'=>12,
                'url'=>"bioparques/losNevados/losNevados-4.jpg"
            ]
            ,
            [
                'place_id'=>12,
                'url'=>"bioparques/losNevados/losNevados-5.jpg"
            ],
            [
                'place_id'=>13,
                'url'=>"bioparques/malpelo/malpelo-1.jpg"
            ]
            ,
            [
                'place_id'=>13,
                'url'=>"bioparques/malpelo/malpelo-2.jpg"
            ]
            ,
            [
                'place_id'=>13,
                'url'=>"bioparques/malpelo/malpelo-3.jpg"
            ]
            ,
            [
                'place_id'=>13,
                'url'=>"bioparques/malpelo/malpelo-4.jpg"
            ]
            ,
            [
                'place_id'=>13,
                'url'=>"bioparques/malpelo/malpelo-5.jpg"
            ],
            [
                'place_id'=>14,
                'url'=>"bioparques/mcbean/mcbean-1.jpg"
            ]
            ,
            [
                'place_id'=>14,
                'url'=>"bioparques/mcbean/mcbean-2.jpg"
            ]
            ,
            [
                'place_id'=>14,
                'url'=>"bioparques/mcbean/mcbean-3.jpg"
            ]
            ,
            [
                'place_id'=>14,
                'url'=>"bioparques/mcbean/mcbean-4.jpg"
            ]
            ,
            [
                'place_id'=>14,
                'url'=>"bioparques/mcbean/mcbean-5.jpg"
            ],
            [
                'place_id'=>15,
                'url'=>"bioparques/santurban/santurban-1.jpg"
            ]
            ,
            [
                'place_id'=>15,
                'url'=>"bioparques/santurban/santurban-2.jpg"
            ]
            ,
            [
                'place_id'=>15,
                'url'=>"bioparques/santurban/santurban-3.jpg"
            ]
            ,
            [
                'place_id'=>15,
                'url'=>"bioparques/santurban/santurban-4.jpg"
            ]
            ,
            [
                'place_id'=>15,
                'url'=>"bioparques/santurban/santurban-5.jpg"
            ],
            [
                'place_id'=>16,
                'url'=>"bioparques/sierraMacarena/sierraMacarena-1.jpg"
            ]
            ,
            [
                'place_id'=>16,
                'url'=>"bioparques/sierraMacarena/sierraMacarena-2.jpg"
            ]
            ,
            [
                'place_id'=>16,
                'url'=>"bioparques/sierraMacarena/sierraMacarena-3.jpg"
            ]
            ,
            [
                'place_id'=>16,
                'url'=>"bioparques/sierraMacarena/sierraMacarena-4.jpg"
            ]
            ,
            [
                'place_id'=>16,
                'url'=>"bioparques/sierraMacarena/sierraMacarena-5.jpg"
            ],
            [
                'place_id'=>17,
                'url'=>"bioparques/sierraNevada/sierraNevada-1.jpg"
            ]
            ,
            [
                'place_id'=>17,
                'url'=>"bioparques/sierraNevada/sierraNevada-2.jpg"
            ]
            ,
            [
                'place_id'=>17,
                'url'=>"bioparques/sierraNevada/sierraNevada-3.jpg"
            ]
            ,
            [
                'place_id'=>17,
                'url'=>"bioparques/sierraNevada/sierraNevada-4.jpg"
            ]
            ,
            [
                'place_id'=>17,
                'url'=>"bioparques/sierraNevada/sierraNevada-5.jpg"
            ],
            [
                'place_id'=>18,
                'url'=>"bioparques/tayrona/tayrona-1.jpg"
            ]
            ,
            [
                'place_id'=>18,
                'url'=>"bioparques/tayrona/tayrona-2.jpg"
            ]
            ,
            [
                'place_id'=>18,
                'url'=>"bioparques/tayrona/tayrona-3.jpg"
            ]
            ,
            [
                'place_id'=>18,
                'url'=>"bioparques/tayrona/tayrona-4.jpg"
            ]
            ,
            [
                'place_id'=>18,
                'url'=>"bioparques/tayrona/tayrona-5.jpg"
            ],
            [
                'place_id'=>19,
                'url'=>"bioparques/tuparro/tuparro-1.jpg"
            ]
            ,
            [
                'place_id'=>19,
                'url'=>"bioparques/tuparro/tuparro-2.jpg"
            ]
            ,
            [
                'place_id'=>19,
                'url'=>"bioparques/tuparro/tuparro-3.jpg"
            ]
            ,
            [
                'place_id'=>19,
                'url'=>"bioparques/tuparro/tuparro-4.jpg"
            ]
            ,
            [
                'place_id'=>19,
                'url'=>"bioparques/tuparro/tuparro-5.jpg"
            ],
            [
                'place_id'=>20,
                'url'=>"bioparques/ultria/ultria-1.jpg"
            ]
            ,
            [
                'place_id'=>20,
                'url'=>"bioparques/ultria/ultria-2.jpg"
            ]
            ,
            [
                'place_id'=>20,
                'url'=>"bioparques/ultria/ultria-3.jpg"
            ]
            ,
            [
                'place_id'=>20,
                'url'=>"bioparques/ultria/ultria-4.jpg"
            ]
            ,
            [
                'place_id'=>20,
                'url'=>"bioparques/ultria/ultria-5.jpg"
            ]
        ];
        foreach ($images as $image) {
            GalleryPlaces::create($image);
        }
    }
}
